### ISSUE TITLE
grammar error 'stucked'

### ISSUE THREAD

**Issue by patrick0057** [thyarles/knsk#18]
Hi thyarles, thank you for this amazing script.  Quick note, "stucked" should be "stuck".

**Comment by thyarles** [comment]
Hi @patrick0057, thank you! I'm looked at the code, there a lot of the words "stucked"... all of them need to be changed? For example:

```
--delete-resource     Delete resources found in your **stucked** namespaces
--delete-all          Delete resources of **stucked** namespaces and broken API
--force               Force deletion of **stucked** namespaces even if a clean deletion fail
```

Could you, please, paste here the full sentence?

Thanks.

**Comment by patrick0057** [comment]
Hi @thyarles yes all occurrences of "stucked" should be "stuck".  You can just run a search and replace on everything for the word "stucked".  "Stucked" isn't actually a word but I understand what you mean when using it in your script and README.md.  You mean the past tense of "stick" which is "stuck".

**Comment by thyarles** [comment]
> Hi @thyarles yes all occurrences of "stucked" should be "stuck". You can just run a search and replace on everything for the word "stucked". "Stucked" isn't actually a word but I understand what you mean when using it in your script and README.md. You mean the past tense of "stick" which is "stuck".

Awesome, @patrick0057!! Done.

Thank you for the lesson. Now my English is a bit better.
