### ISSUE TITLE
feedbak: namespace still exists after knsk run

### ISSUE THREAD

**Issue by fawzikds** [thyarles/knsk#19]
hi,
I just tested out your script on a stuck namespace (nextcloud).  The script was able to identify it but even though it reported success in deleting it, it actually did not.
here is the output of the run:

```
root@kdsha:/home/kdsha# ./knsk.sh --delete-all --force
Kubernetes NameSpace Killer
Checking if kubectl is configured... ok
Checking for unavailable apiservices... not found
Checking for stuck namespaces... found
.: Checking resources in namespace nextcloud... not found
Checking for stuck resources in the cluster... not found
Checking for orphan resources in the cluster... not found
Forcing deletion of stuck namespaces
.: Checking compliance of --force option... ok
.: Getting the access token to force deletion... ok
.: Starting kubectl proxy... ok
.: Checking for resisted stuck namespaces to force deletion... found
   > Forcing deletion of nextcloud... ok
.: Stopping kubectl proxy... ok
:: Done in 41 seconds.

root@kdsha:/home/kdsha# kubectl get namespaces
NAME              STATUS        AGE
default           Active        4d21h
kube-node-lease   Active        4d21h
kube-public       Active        4d21h
kube-system       Active        4d21h
nextcloud         Terminating   23h
```

**Comment by thyarles** [comment]
Hi, @fawzikds.

Could you please paste here the output of the file /tmp/nextcloud.json?

**Comment by fawzikds** [comment]
HI Charles,
 
i couldn't find such file.
 
any other location to look into?
 
I have resolved the issue although i can't remember how exactly right now.
 
 
 
 
 
 
-----Original Message-----

**Comment by thyarles** [comment]
Glad to hear that it was solved. I think you got something like that: https://github.com/thyarles/knsk/issues/15

I'll close it now, if you have trouble again, please, reopen it.

Thanks.
