### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [thyarles/knsk#2]
```
 [root@node1 ~]# curl -s https://raw.githubusercontent.com/thyarles/knsk/master/knsk.sh | sh
\nKubernetes namespace killer\n
- Testing if kubectl is configured... ok!\n
- Cheking for unavailable apiservices... found:\n
  -- v1beta1.custom.metrics.k8s.io (not available)
\n  Should I delete it for you (yes/[no])? >
\tOk, the right way is delete not available apiservices resources, check it on
\thttps://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920\n
\tIf you want to delete by yourself later, run:\n
\tkubectl delete apiservice v1beta1.custom.metrics.k8s.io

- Checking for namespaces in Terminating status... found!\n
  -- Cheking resources in namespace knative-serving... not found!\n
- Checking again for namespaces in Terminating status... found!\n
  -- Getting the access token to force deletion... ok!\n
  -- Starting kubectl proxy... ok!\n
  >> Forcing deletion of knative-serving... ok!
\n  -- Stopping kubectl proxy... ok!\n
Done! Please, check if your stucked namespace was deleted!\n




[root@node1 ~]# kubectl delete apiservice v1beta1.custom.metrics.k8s.io
apiservice.apiregistration.k8s.io "v1beta1.custom.metrics.k8s.io" deleted
[root@node1 ~]# kubectl delete apiservice v1beta1.custom.metrics.k8s.io
Error from server (NotFound): apiservices.apiregistration.k8s.io "v1beta1.custom.metrics.k8s.io" not found


[root@node1 ~]# curl -s https://raw.githubusercontent.com/thyarles/knsk/master/knsk.sh | sh
\nKubernetes namespace killer\n
- Testing if kubectl is configured... ok!\n
- Cheking for unavailable apiservices... not found!\n
- Checking for namespaces in Terminating status... found!\n
  -- Cheking resources in namespace knative-serving... not found!\n
- Checking again for namespaces in Terminating status... found!\n
  -- Getting the access token to force deletion... ok!\n
  -- Starting kubectl proxy... ok!\n
  >> Forcing deletion of knative-serving... ok!
\n  -- Stopping kubectl proxy... ok!\n
Done! Please, check if your stucked namespace was deleted!\n


[root@node1 ~]# ./del-ns.sh knative-serving
No such namespace named knative-serving

```

**Comment by thyarles** [comment]
Hi @Pomazan-Bogdan,

Thanks for reporting. Please, could out check the content of the files  **/tmp/NAMSPACE_NAME.json** and **/tmp/NAMESPACE_NAME.json.out**? I think that the call to Kubernetes API (that forces deletion when clean deletion doesn't work) isn't working for you.

Another thing you can try is use the first version of the script, it is much more simpler, but don't try to delete namespaces in a clean way before do a hard deletion... could you try to use it? Here is the first version: https://raw.githubusercontent.com/thyarles/knsk/3de1bfd5aa9bbd1848c4c9a493df4abf4fc6b91f/knsk.sh

Regards.

**Comment by Pomazan-Bogdan** [comment]
I dont have this klaster (

**\t**kubectl delete apiservice v1beta1.custom.metrics.k8s.io ?

**Comment by Pomazan-Bogdan** [comment]
```
[centos@srv1 ~]$ curl -s https://raw.githubusercontent.com/thyarles/knsk/master/knsk.sh | sh
\nKubernetes namespace killer\n
- Testing if kubectl is configured... ok!\n
- Cheking for unavailable apiservices... found:\n
  -- v1alpha1.tap.linkerd.io (not available)
  -- v1beta1.metrics.k8s.io (not available)
\n  Should I delete it for you (yes/[no])? >
\tOk, the right way is delete not available apiservices resources, check it on
\thttps://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920\n
\tIf you want to delete by yourself later, run:\n
\tkubectl delete apiservice v1alpha1.tap.linkerd.io
\tkubectl delete apiservice v1beta1.metrics.k8s.io

- Checking for namespaces in Terminating status... found!\n
  -- Cheking resources in namespace linkerd... not found!\n
  -- Cheking resources in namespace cattle-system... not found!\n
  -- Cheking resources in namespace cattle-global-data... not found!\n
  -- Cheking resources in namespace lens-metrics... not found!\n
- Checking again for namespaces in Terminating status... found!\n
  -- Getting the access token to force deletion... ok!\n
  -- Starting kubectl proxy... ok!\n
  >> Forcing deletion of linkerd... ok!
  >> Forcing deletion of cattle-system... ok!
  >> Forcing deletion of cattle-global-data... ok!
  >> Forcing deletion of lens-metrics... ok!
\n  -- Stopping kubectl proxy... ok!\n
Done! Please, check if your stucked namespace was deleted!\n
[centos@srv1 ~]$ kubectl delete apiservice v1alpha1.tap.linkerd.io
apiservice.apiregistration.k8s.io "v1alpha1.tap.linkerd.io" deleted
[centos@srv1 ~]$ kubectl delete apiservice v1beta1.metrics.k8s.io
apiservice.apiregistration.k8s.io "v1beta1.metrics.k8s.io" deleted

```

I think this command don't run in script:
\tkubectl delete apiservice v1alpha1.tap.linkerd.io
\tkubectl delete apiservice v1beta1.metrics.k8s.io

**Comment by Pomazan-Bogdan** [comment]
> Hi @Pomazan-Bogdan,
> 
> Thanks for reporting. Please, could out check the content of the files **/tmp/NAMSPACE_NAME.json** and **/tmp/NAMESPACE_NAME.json.out**? I think that the call to Kubernetes API (that forces deletion when clean deletion doesn't work) isn't working for you.
> 
> Another thing you can try is use the first version of the script, it is much more simpler, but don't try to delete namespaces in a clean way before do a hard deletion... could you try to use it? Here is the first version: https://raw.githubusercontent.com/thyarles/knsk/3de1bfd5aa9bbd1848c4c9a493df4abf4fc6b91f/knsk.sh
> 
> Regards.

./knsk.sh
./knsk.sh: line 23: [: too many arguments
No namespage in Terminating status found

**Comment by thyarles** [comment]
**> Should I delete it for you (yes/[no])? >**

Are you answering **YES** here? The default is **NO**. Or the script don't wait for your response? 

What version of sh are you using? I think you using **bash** and not **dash**... try to run:

```
root@server ~]# ls -lah /usr/bin/sh
lrwxrwxrwx 1 root root 4 Oct  1 14:39 /usr/bin/sh -> bash
```

I'll try to adjust the code to run in bash. 

Thanks!

**Comment by Pomazan-Bogdan** [comment]
> **> Should I delete it for you (yes/[no])? >**
> 
> Are you answering **YES** here? The default is **NO**. Or the script don't wait for your response?

Script dont answer. His keep this answer in run

**Comment by Pomazan-Bogdan** [comment]
> root@server ~]# ls -lah /usr/bin/sh
> lrwxrwxrwx 1 root root 4 Oct  1 14:39 /usr/bin/sh -> bash

`lrwxrwxrwx. 1 root root 4 Oct  1 15:27 /usr/bin/sh -> bash`

**Comment by Pomazan-Bogdan** [comment]
May be add "kubectl delete crd --namespace &namespace --all" in script before delete namespace?

**Comment by thyarles** [comment]
> May be add "kubectl delete crd --namespace &namespace --all" in script before delete namespace?

Sure, I'll try it when I'll refactor it to work with **bash** instead of **dash**.

Thank you.

**Comment by thyarles** [comment]
Fixed. 

Please, if you see the error again, fell free to report, @Pomazan-Bogdan. Thanks.

**Comment by Pomazan-Bogdan** [comment]
((
Not work
Script dont send 
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -n NAMESPACE

**Comment by Pomazan-Bogdan** [comment]
`
Kubernetes namespace killer

- Testing if kubectl is configured... ok!

- Cheking for unavailable apiservices... not found!

- Checking for namespaces in Terminating status... found!

  -- Cheking resources in namespace linkerd... found!

     --- pod/linkerd-grafana-8c544b7bf-mkxwg
     --- pod/linkerd-prometheus-6c99767cd7-lv6cs
     --- pod/linkerd-destination-68cb95c855-7z8jc
     --- pod/linkerd-proxy-injector-6c7b5c5db5-jr5ng
     --- pod/linkerd-identity-7cf96c8476-gqvq2
     --- pod/linkerd-controller-656ddcdcf6-t2289
     --- pod/linkerd-sp-validator-66789c4556-89scz
     --- pod/linkerd-web-f9d6cb99d-lbz8v
     --- pod/linkerd-tap-795fd8c58c-qz8hh
     --- podmetrics.metrics.k8s.io/linkerd-sp-validator-66789c4556-89scz
     --- podmetrics.metrics.k8s.io/linkerd-grafana-8c544b7bf-mkxwg

     Should I delete it for you (yes/[no])? > 
	Ok, the right way is delete not available apiservices resources, check it on
	https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920

  -- Cheking resources in namespace lens-metrics... found!

     --- persistentvolumeclaim/data-prometheus-0
     --- pod/node-exporter-vkkfj
     --- pod/node-exporter-5xm2b
     --- pod/prometheus-0
     --- pod/kube-state-metrics-675fd8dc5d-pfz4p
     --- podmetrics.metrics.k8s.io/node-exporter-vkkfj
     --- podmetrics.metrics.k8s.io/node-exporter-5xm2b
     --- podmetrics.metrics.k8s.io/kube-state-metrics-675fd8dc5d-pfz4p

     Should I delete it for you (yes/[no])? > 
	Ok, the right way is delete not available apiservices resources, check it on
	https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920

  -- Cheking resources in namespace tekton-pipelines... found!

     --- pod/tekton-pipelines-controller-55f95fbb9b-krqhk
     --- pod/tekton-pipelines-webhook-6dd8446c85-4kr97
     --- podmetrics.metrics.k8s.io/tekton-pipelines-controller-55f95fbb9b-krqhk

     Should I delete it for you (yes/[no])? > 
	Ok, the right way is delete not available apiservices resources, check it on
	https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920

  -- Cheking resources in namespace rio-system... found!

     --- persistentvolumeclaim/rio-registry
     --- pod/svclb-gateway-proxy-v2-2r9bb
     --- pod/rio-controller-6b65fbb9d6-72m8z
     --- pod/svclb-gateway-proxy-v2-7j8qx
     --- pod/buildkitd-cd45c5c65-6rwpf
     --- pod/svclb-gateway-proxy-v2-5f6kj
     --- pod/cert-manager-cd6f46cfd-lbzdf
     --- pod/gloo-75895cb6f8-8h5p8
     --- pod/dashboard-8545d57d66-dsw7d
     --- pod/gateway-v2-75b45787c6-st2mr
     --- pod/gateway-proxy-v2-6747d6fcfd-ssvk8
     --- pod/webhook-8dd6fd5cb-tvvpl
     --- pod/autoscaler-64d6db4b6c-tg4ft
     --- podmetrics.metrics.k8s.io/autoscaler-64d6db4b6c-tg4ft
     --- podmetrics.metrics.k8s.io/gateway-proxy-v2-6747d6fcfd-ssvk8
     --- podmetrics.metrics.k8s.io/cert-manager-cd6f46cfd-lbzdf
     --- podmetrics.metrics.k8s.io/svclb-gateway-proxy-v2-2r9bb

     Should I delete it for you (yes/[no])? > 
	Ok, the right way is delete not available apiservices resources, check it on
	https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920


- Waiting a minute to see if Kubernetes do a clean namespace deletion... 01:00

- Waiting a minute to see if Kubernetes do a clean namespace deletion... 00:01
- Waiting a minutes to see if Kubernetes do a clean namespace deletion... ok!  `

**Comment by Pomazan-Bogdan** [comment]
Next, i put manual:
`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -n linkerd
No resources found in linkerd namespace.

NAME                                      READY   STATUS        RESTARTS   AGE
linkerd-grafana-8c544b7bf-mkxwg           0/2     Terminating   12         7d3h
linkerd-prometheus-6c99767cd7-lv6cs       0/2     Terminating   0          66m
linkerd-destination-68cb95c855-7z8jc      0/2     Terminating   2          7d3h
linkerd-proxy-injector-6c7b5c5db5-jr5ng   0/2     Terminating   2          7d3h
linkerd-identity-7cf96c8476-gqvq2         0/2     Terminating   2          7d3h
linkerd-controller-656ddcdcf6-t2289       0/3     Terminating   3          7d3h
linkerd-sp-validator-66789c4556-89scz     0/2     Terminating   0          7d3h
linkerd-web-f9d6cb99d-lbz8v               0/2     Terminating   2          7d3h
linkerd-tap-795fd8c58c-qz8hh              0/2     Terminating   2          7d3h
No resources found in linkerd namespace.

NAME                                    AGE
linkerd-grafana-8c544b7bf-mkxwg         0s
linkerd-sp-validator-66789c4556-89scz   0s

No resources found in linkerd namespace.
`

**Comment by Pomazan-Bogdan** [comment]
Maybe add full log in script?
