### ISSUE TITLE
No issue.. Just a "Thank you" for a wonderful script!

### ISSUE THREAD

**Issue by fmbahrt** [thyarles/knsk#20]
*<[:-)

**Comment by thyarles** [comment]
Hi @fmbahrt! 

Thank you a million! I really appreciate your time just to say it. As I manage more than 10 clusters, I scheduled this script to run in the basic form on all every day just to make sure they all are working as expected, without stuck or orphan resources, sending the report by email with the results. The time to run the script is also observed, if it increase a lot from one day to another, maybe it is a sing that the apiservers and/or the etcd servers are running over pressure.

Again, thank you.

**Comment by markbaumgarten** [comment]
Until i found this script I was lying with my head on the keyboard reconsidering my choice of career. Your script saved my day. Thanks!

**Comment by thyarles** [comment]
Hello, @markbaumgarten! Thank you very much, I'm very happy to see that the script is helping other people. I did it exactly for that reason: it was disheartening to have to repeat all the commands on all the features of the k8s just to see why some feature stuck. It was then that the idea to automate these steps in this script was born. I am currently studying Go to create a version of this tool that will run on any operating system.
