### ISSUE TITLE
using --type=merge to delete a stubborn CRD

### ISSUE THREAD

**Issue by sjwl** [thyarles/knsk#29]
I had a stubborn terminating ns that wouldn't delete even after running knsk with force.
```
cat /tmp/razee.json.log
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the body of the request was in an unknown format - accepted media types include: application/json, application/yaml, application/vnd.kubernetes.protobuf",
  "reason": "UnsupportedMediaType",
  "code": 415
}
```

Running the command below would produce the same error.
```
kubectl -n razee patch remoteresource.deploy.razee.io/razeedash -p '{"metadata":{"finalizers":null}}'
```

So this stackoverflow [answer](https://stackoverflow.com/questions/57480205/error-while-applying-json-patch-to-kubernetes-custom-resource) led me to run this command

```
kubectl -n razee patch remoteresource.deploy.razee.io/razeedash --type=merge -p '{"metadata":{"finalizers":null}}'
```
and it worked!  my namespace deleted after that.

**Comment by thyarles** [comment]
Suggestion noted and will be implemented when I have some free time. Thanks.
