### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by ChrisScottThomas** [thyarles/knsk#3]
Hello!  This works, but assumes Linux!

Your sed fails on OSX:  
`sed -i s/\"kubernetes\"//g $j`  

wants to be:
`sed -i '' "s/\"kubernetes\"//g" $j`  
for OSX.

You could do a:

```
if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/\"kubernetes\"//g" $j
  else
    sed -i s/\"kubernetes\"//g $j
  fi
``` 

Also my proxy by default is on 8001, yet you call it on 8002?  Another OS thing?

**Comment by thyarles** [comment]
Hello @ChrisScottThomas,

Good call, thanks for your comments.

I'll change like you show to work on MacOS. I'll check about the proxy's port too!

**Comment by thyarles** [comment]
FIxed! Thanks for your tip, @ChrisScottThomas.
